#!/usr/bin/env python

"""Extracts a PSF profile from a fits image."""

import os
import sys
from specklepy.logging import logger
import specklepy.scripts.get_psf_profile as script

if __name__ == '__main__':

    try:
        script.main()
    except KeyboardInterrupt:
        logger.info('Interrupted by user...')
        try:
            sys.exit(0)
        except SystemExit:
            os._exit(0)