#!/usr/bin/env python

"""Executes Specklepy data reduction following a parameter file."""

import os
import sys
from specklepy.logging import logger
import specklepy.deprecated.reduction as script

if __name__ == '__main__':
    try:
        script.main()
    except KeyboardInterrupt:
        logger.info('Interrupted by user...')
        try:
            sys.exit(0)
        except SystemExit:
            os._exit(0)